version: '3.8'
services:
  # app:
  #   build: .
  #   volumes:
  #      - ./src:/app/src 
  #   environment:
  #     - PORT=4000
  #   ports:
  #     - "4000:4000"
  #   command: ["npm", "run", "start:dev"]
  #   restart: unless-stopped

#   db:
#     image: postgres:latest
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=mydatabase
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#     restart: unless-stopped

# volumes:
#   db-data:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
